### ISSUE TITLE
能问下这个这么在window上跑起来吗？

### ISSUE THREAD

**Issue by zhengxs2018** [FeifeiyuM/koa2-typescript#1]
所有的环境都准备好了，可是就是不行，谷歌了之后，看到类似的问题，但是没看懂他们最后的解决办法是什么

![image](https://cloud.githubusercontent.com/assets/7506913/24488914/c332e462-154c-11e7-9165-e547bc842cde.png)

**Comment by FeifeiyuM** [comment]
[Windows - pm2 install typescript](https://github.com/Unitech/pm2/issues/2675) 这个问题好像还是处于 open 状态。你可以换一种方式运行， 把 typescript 先转译成 js,  在通过 node 启动工程

**Comment by FeifeiyuM** [comment]
你看下，我在 README 里面提供了一个解决方案， 你看下行不行

**Comment by zhengxs2018** [comment]
我试试，不过今天不行了，因为今天我们公司搬家，O(∩_∩)O谢谢
